version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: namaphdb
    tty: true
    networks:
      - namaph-network
    volumes:
      - "./namaphio/data:/data"

  apiserver:
    build: 
      context: ./namaphio
    image: namaphio
    container_name: namaphio
    tty: true
    networks:
      - namaph-network
    ports:
      - "8080:8080"
    depends_on:
      - redis

networks:
  namaph-network:
