redis:
  host: localhost
  port: 6379
  db:
    - 0 # List of table
    - 1 # Local Data
    - 2 # Module Data
    - 3 # Fetching Data

cityio:
  host: https://cityio.media.mit.edu/api
  methods:
    ListTables: /tables/list
    GetTable: /table/{table}
    PostTable: /table/update/{table}/{field}
    DeleteTable: /table/clear/{table}/{field}
    
